[0m06:09:25.347009 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b4e2e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074219a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107421b80>]}


============================== 06:09:25.367611 | 54b0857f-4bdc-447d-99e3-44381576bf69 ==============================
[0m06:09:25.367611 [info ] [MainThread]: Running with dbt=1.10.11
[0m06:09:25.368019 [debug] [MainThread]: running dbt with arguments {'warn_error': 'None', 'use_experimental_parser': 'False', 'debug': 'False', 'empty': 'None', 'write_json': 'True', 'partial_parse': 'True', 'target_path': 'None', 'cache_selected_only': 'False', 'log_format': 'default', 'log_cache_events': 'False', 'log_path': 'logs', 'invocation_command': 'dbt init', 'printer_width': '80', 'introspect': 'True', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'fail_fast': 'False', 'profiles_dir': '/Users/omondidenzel/.dbt', 'version_check': 'True', 'use_colors': 'True', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager'}
[0m06:09:59.261050 [debug] [MainThread]: Starter project path: /Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/include/starter_project
[0m06:09:59.273681 [info ] [MainThread]: 
Your new dbt project "sap_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m06:09:59.274353 [info ] [MainThread]: Setting up your profile.
[0m06:10:09.399137 [error] [MainThread]: Encountered an error:
dlopen(/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib
  Referenced from: <7F70FA82-3FAB-3479-B9E8-F86B87F9FEF0> /Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so
  Reason: tried: '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file)
[0m06:10:09.450956 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/task/init.py", line 172, in create_profile_from_target
    load_plugin(adapter)
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/adapters/factory.py", line 239, in load_plugin
    return FACTORY.load_plugin(name)
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/adapters/factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/adapters/postgres/__init__.py", line 4, in <module>
    from dbt.adapters.postgres.connections import PostgresConnectionManager, PostgresCredentials
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/adapters/postgres/connections.py", line 15, in <module>
    import psycopg2
  File "/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib
  Referenced from: <7F70FA82-3FAB-3479-B9E8-F86B87F9FEF0> /Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so
  Reason: tried: '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file)

[0m06:10:09.477642 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 44.184105, "process_in_blocks": "0", "process_kernel_time": 0.478624, "process_mem_max_rss": "122798080", "process_out_blocks": "0", "process_user_time": 1.795801}
[0m06:10:09.478382 [debug] [MainThread]: Command `dbt init` failed at 06:10:09.478225 after 44.19 seconds
[0m06:10:09.478891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b4e2e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073e3070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070ce520>]}
[0m06:10:09.479339 [debug] [MainThread]: Flushing usage events
[0m06:10:11.131790 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:13:07.878714 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10734d160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083c3520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083c3340>]}


============================== 06:13:07.882045 | 0b4dba80-e88c-4ec6-8d49-cdf0942f64bf ==============================
[0m06:13:07.882045 [info ] [MainThread]: Running with dbt=1.10.11
[0m06:13:07.882417 [debug] [MainThread]: running dbt with arguments {'profiles_dir': '/Users/omondidenzel/.dbt', 'partial_parse': 'True', 'introspect': 'True', 'version_check': 'True', 'indirect_selection': 'eager', 'quiet': 'False', 'log_format': 'default', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'use_colors': 'True', 'log_path': 'logs', 'cache_selected_only': 'False', 'use_experimental_parser': 'False', 'static_parser': 'True', 'fail_fast': 'False', 'warn_error': 'None', 'write_json': 'True', 'target_path': 'None', 'empty': 'None', 'send_anonymous_usage_stats': 'True', 'debug': 'False', 'no_print': 'None', 'printer_width': '80', 'log_cache_events': 'False', 'invocation_command': 'dbt init'}
[0m06:13:15.947564 [debug] [MainThread]: Starter project path: /Users/omondidenzel/Desktop/DBT-Pipeline/venv/lib/python3.9/site-packages/dbt/include/starter_project
[0m06:13:15.961502 [info ] [MainThread]: 
Your new dbt project "sap_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m06:13:15.962202 [info ] [MainThread]: Setting up your profile.
[0m06:14:41.151477 [info ] [MainThread]: Profile sap_pipeline written to /Users/omondidenzel/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m06:14:41.160228 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 93.33072, "process_in_blocks": "0", "process_kernel_time": 0.206193, "process_mem_max_rss": "95092736", "process_out_blocks": "0", "process_user_time": 0.863266}
[0m06:14:41.161450 [debug] [MainThread]: Command `dbt init` succeeded at 06:14:41.161181 after 93.33 seconds
[0m06:14:41.162609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10734d160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10836eb20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083f71c0>]}
[0m06:14:41.163412 [debug] [MainThread]: Flushing usage events
[0m06:14:43.139541 [debug] [MainThread]: An error was encountered while trying to flush usage events
